branch-defaults:
  default:
    environment: Default-Environment
environment-defaults:
  Default-Environment:
    branch: null
    repository: null
global:
  application_name: My First Elastic Beanstalk Application
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-south-1::platform/Python 2.7 running
    on 64bit Amazon Linux/2.5.2
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
