# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_fruit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fruit',
        ),
    ]
