# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_delete_fruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
