# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20171015_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='password',
            field=models.CharField(default='Admin@123', max_length=100),
        ),
        migrations.AddField(
            model_name='board',
            name='username',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
